apiVersion: batch/v1
kind: Job
metadata:
  name: naocs-db-init
  namespace: {{ $.Release.Namespace }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - env:
          - name: MYSQL_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                name: nacos-cm
                key: mysql.db.host
          - name: MYSQL_SERVICE_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: nacos-cm
                key: mysql.db.name
          - name: MYSQL_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: nacos-cm
                key: mysql.port
          - name: MYSQL_SERVICE_USER
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.nacos.storage.db.basicAuthSecretName }}"
                key: mysql.user
          - name: MYSQL_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.nacos.storage.db.basicAuthSecretName }}"
                key: mysql.password
          - name: NACOS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.nacos.adminBasicAuthSecretName }}"
                key: password
          name: mysql-init
          image: {{ .Values.global.registry.address }}/{{.Values.global.images.dbInit.repository}}:{{.Values.global.images.dbInit.tag}}
          imagePullPolicy: Always
