{{- if and (eq .Values.global.mode "cluster") }}
apiVersion: v1
kind: Service
metadata:
  name: nacos-hs
  namespace: {{ $.Release.Namespace }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.nacos.serverPort }}
      protocol: TCP
      name: http
    - port: 18848
      targetPort: 18848
      protocol: TCP
      name: mcp
    - port: {{ add .Values.service.port 1000}}
      name: client-rpc
      targetPort: {{add .Values.nacos.serverPort 1000}}
    - port: {{add .Values.service.port 1001}}
      name: raft-rpc
      targetPort: {{add .Values.nacos.serverPort 1001}}
    ## 兼容1.4.x版本的选举端口
    - port: 7848
      name: old-raft-rpc
      targetPort: 7848
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "nacos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
  {{- toYaml .Values.service.labels | nindent 4 }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  {{- if .Values.service.nodePort.enabled }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.nacos.serverPort }}
      protocol: TCP
      name: http
    - port: 18848
      targetPort: 18848
      protocol: TCP
      name: mcp
    - port: {{ add .Values.service.port 1000}}
      name: client-rpc
      targetPort: {{add .Values.nacos.serverPort 1000}}
    - port: {{add .Values.service.port 1001}}
      name: raft-rpc
      targetPort: {{add .Values.nacos.serverPort 1001}}
  selector:
    app.kubernetes.io/name: {{ include "nacos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-manage
  labels:
  {{- toYaml .Values.service.labels | nindent 4 }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.management.port }}
      targetPort: {{ .Values.management.port }}
      protocol: TCP
      name: http
    - port: {{ add .Values.management.port 1000}}
      name: client-rpc
      targetPort: {{add .Values.management.port 1000}}
    - port: {{add .Values.management.port 1001}}
      name: raft-rpc
      targetPort: {{add .Values.management.port 1001}}
  selector:
    app.kubernetes.io/name: {{ include "nacos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
